# Practical 01: Dataset Ingestion, Inspection & Descriptive Statistics with Pandas

**UNIT 1: Introduction to Big Data and Large Dataset Handling**

**Problem Statement:** Write a Python program using Pandas to load a structured dataset (CSV/JSON), display its first 5 rows, last 5 rows, dimensions (shape), column names, and data types with info(). Generate comprehensive summary statistics of all numeric and categorical attributes using describe(include='all').

In [1]:
import io
import numpy as np
import pandas as pd

pd.set_option("display.max_columns", None, "display.width", 200)

rnd = np.random.default_rng(123)
n = 300
seed_df = pd.DataFrame({
    "Order ID": np.arange(1001, 1001 + n),
    "Customer Name": [f"User_{i:03d}" for i in rnd.integers(1, 100, n)],
    "City": rnd.choice(["Surat", "Mumbai", "Pune", "Nagpur", "Thane", "Rajkot"], n),
    "Product Category": rnd.choice(["Electronics", "Clothing", "Groceries", "Furniture", "Beauty"], n),
    "Quantity": rnd.integers(1, 9, n),
    "Unit Price": np.round(rnd.uniform(100, 4000, n), 2),
    "Discount %": rnd.choice([0, 5, 10, 15, 20], n),
    "Order Date": pd.date_range("2025-01-20", periods=n, freq="D").strftime("%Y-%m-%d"),
})

mem_csv = io.StringIO()
seed_df.to_csv(mem_csv, index=False)
mem_csv.seek(0)
mem_json = io.StringIO(seed_df.to_json(orient="records"))

tbl = pd.read_csv(mem_csv)
print("Dataset loaded successfully!")

print(tbl.head())

print(tbl.tail())

print("Shape (rows, columns):", tbl.shape)
print("Column names:", tbl.columns.tolist())

tbl.info()

print(tbl.describe(include='all'))

from_json = pd.read_json(mem_json)
print("JSON load – shape:", from_json.shape)
print(from_json.head())

Dataset loaded successfully!

   Order ID  Customer Name    City  Product Category  Quantity  Unit Price  Discount %  Order Date
0      1001       User_002  Mumbai       Electronics         6      196.59          15  2025-01-20
1      1002       User_068   Surat          Clothing         5     3846.09          15  2025-01-21
2      1003       User_059  Mumbai         Groceries         1     3809.61          10  2025-01-22
3      1004       User_006    Pune         Groceries         1     1092.32          20  2025-01-23
4      1005       User_090   Surat         Furniture         3     2827.17           5  2025-01-24

     Order ID  Customer Name    City  Product Category  Quantity  Unit Price  Discount %  Order Date
295      1296       User_046  Rajkot            Beauty         3      200.04          10  2025-11-11
296      1297       User_049   Surat         Groceries         8     3868.55          15  2025-11-12
297      1298       User_004    Pune          Clothing         2     1477.77          15  2025-11-13
298      1299       User_087    Pune       Electronics         1     2281.61          10  2025-11-14
299      1300       User_032    Pune            Beauty         2     1983.38          20  2025-11-15

Shape (rows, columns): (300, 8)
Column names: ['Order ID', 'Customer Name', 'City', 'Product Category', 'Quantity', 'Unit Price', 'Discount %', 'Order Date']
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Order ID          300 non-null    int64
 1   Customer Name     300 non-null    object
 2   City              300 non-null    object
 3   Product Category  300 non-null    object
 4   Quantity          300 non-null    int64
 5   Unit Price        300 non-null    float64
 6   Discount %        300 non-null    int64
 7   Order Date        300 non-null    object
dtypes: float64(1), int64(3), object(4)
memory usage: 18.9+ KB

           Order ID  Customer Name   City  Product Category    Quantity   Unit Price  Discount %  Order Date
 count   300.000000            300    300               300  300.000000   300.000000  300.000000         300
unique          NaN             92      6                 5         NaN          NaN         NaN         300
   top          NaN       User_018  Thane       Electronics         NaN          NaN         NaN  2025-01-20
  freq          NaN              8     65                62         NaN          NaN         NaN           1
  mean  1150.500000            NaN    NaN               NaN    4.583333  1962.110167   10.883333         NaN
   std    86.746758            NaN    NaN               NaN    2.355465  1068.384725    7.104315         NaN
   min  1001.000000            NaN    NaN               NaN    1.000000   113.720000    0.000000         NaN
   25%  1075.750000            NaN    NaN               NaN    2.000000  1062.887500    5.000000         NaN
   50%  1150.500000            NaN    NaN               NaN    5.000000  1984.720000   10.000000         NaN
   75%  1225.250000            NaN    NaN               NaN    7.000000  2801.442500   15.000000         NaN
   max  1300.000000            NaN    NaN               NaN    8.000000  3998.470000   20.000000         NaN

JSON load – shape: (300, 8)

   Order ID  Customer Name    City  Product Category  Quantity  Unit Price  Discount %  Order Date
0      1001       User_002  Mumbai       Electronics         6      196.59          15  2025-01-20
1      1002       User_068   Surat          Clothing         5     3846.09          15  2025-01-21
2      1003       User_059  Mumbai         Groceries         1     3809.61          10  2025-01-22
3      1004       User_006    Pune         Groceries         1     1092.32          20  2025-01-23
4      1005       User_090   Surat         Furniture         3     2827.17           5  2025-01-24